### ISSUE TITLE
请教问题

### ISSUE THREAD

**Issue by leileilin** [ictnlp/COKD#1]
你好，非常感谢开源这么棒的工作，细读你的论文之后，我有一个疑惑，在消融实验中-CT我不是很懂，-CT不是代表没有教师模型，那整体性能不是应该等于transformer的性能吗？

谢谢！！！！

**Comment by shaochenze** [comment]
你好，感谢关注我们的工作！CT表示我们用设计好的数据顺序来保证教师与学生的互补性，- CT就表示教师与学生训练的数据顺序是随机的。这种情况下，互补性仍存在，但会被减弱，所以性能会略微低一些。

**Comment by shaochenze** [comment]
close issue
