### ISSUE TITLE
Data Split

### ISSUE THREAD

**Issue by dsj96** [ictnlp/COKD#2]
Hello, Shao! This is a great work! In this paper, `Specifically, in each epoch, we divide the training dataset D into n+1 mutually exclusive splits (D1;D2;...;Dn+1).`, I wonder how this dataset is splited, Could you describe it in more detail? (I think the split method of the dataset may affect the results.)
And does each Di (1≤i≤n+1) has its own test dataset or test dataset is identical in each Di? Thanks!

**Comment by shaochenze** [comment]
Thanks for your interests in our work. The dataset D consists of N batches. In each epoch,  we shuffle the batches and  divide the training dataset D into n+1 splits. For example, if N=100 and n=9, then D1 consists of the first 10 batches, D2 consists of the 11-20 batches,..., D10 consists of the 91-100 batches. The test dataset is identical in each Di.

**Comment by dsj96** [comment]
Is D1 in epoch 1 and D1 in epoch 2 maybe different?

**Comment by shaochenze** [comment]
Yes, data splits in every epoch are different.

**Comment by dsj96** [comment]
Thank you for your reply!
